### ISSUE TITLE
Error after reading QR code to link other device in the WhatsApp application

### ISSUE THREAD

**Issue by gauyaba** [noelzappy/chatgpt-whatsapp#2]
I'm getting to the point where I'm authenticating in the Open.AI site, the QR code show up in my terminal and then after I read the QR code to link other device in my WhatsApp application, I'm getting the following error:
--------
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')
    at __puppeteer_evaluation_script__:13:76
    at ExecutionContext._evaluateInternal (/Users/cesarsalazar/chatgpt-whatsapp/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/Users/cesarsalazar/chatgpt-whatsapp/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.initialize (/Users/cesarsalazar/chatgpt-whatsapp/node_modules/whatsapp-web.js/src/Client.js:267:9)

Node.js v18.13.0
error Command failed with exit code 1.
------

The error message is saying that the script is trying to read a property of an undefined object, specifically the property 'LegacyPhoneFeatures'. where this object is? how to fix it?

**Comment by noelzappy** [comment]
Hi, @gauyaba I will try and see if I can reproduce this and apply a fix.

From what I understand, you get the error when you scan the QR code generated using your WhatsApp right? What type of WhatsApp(Business or regular) are you using?

**Comment by gauyaba** [comment]
Hi @noelzappy, I'm using a regular WhatsApp app/account. The error happens few seconds after I scan the QR with WhatsApp in my cell. I'm using Mac OS and just installed chrome for this purpose. Thanks for your support!

**Comment by noelzappy** [comment]
hi @gauyaba, The issue seems to be related to the whatsapp-web-js library I used. However, I have upgraded the package to the latest version which was the suggested solution on their GitHub issues, you can do the same in your clone or pull the changes and let me know if that resolves the issue for you.

**Comment by MrNhanh** [comment]
Hi @noelzappy , I'm using a regulare WhatsApp app. And I get this error:

C:\Users\Asus\chatgpt-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExists')
    at __puppeteer_evaluation_script__:25:69
    at ExecutionContext._evaluateInternal (C:\Users\Asus\chatgpt-whatsapp\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (C:\Users\Asus\chatgpt-whatsapp\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
    at Client.initialize (C:\Users\Asus\chatgpt-whatsapp\node_modules\whatsapp-web.js\src\Client.js:267:9)

Node.js v18.14.0
error Command failed with exit code 1.

**Comment by noelzappy** [comment]
This issue should now be resolved. Pull in a fresh copy and try again.
